import { MailListItemProps } from "../common/ui-kit/MailListItem/MailListItem.interface";

export const mails: MailListItemProps[] = [
  {
    id: "1",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "2",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: true,
  },
  {
    id: "3",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "4",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "5",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "6",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "7",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "8",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: true,
  },
  {
    id: "9",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
  {
    id: "10",
    sender: "Atlassian",
    title: "Introducing Table Visualization",
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: "16 июн.",
    isViewed: false,
  },
];
