export interface Mail {
  id: string;
  sender: string;
  title: string;
  text: string;
  date: string;
  isViewed: boolean;
}

export const mails: Mail[] = [
  {
    id: '1',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '2',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '3',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '4',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '5',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '6',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '7',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '8',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '9',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '10',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '11',
    sender: 'Atlassian',
    title: 'SecondPage',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '12',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '13',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '14',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '15',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '16',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '17',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '18',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '19',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '20',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '21',
    sender: 'Atlassian',
    title: 'ThirdPage',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '22',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '23',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '24',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '25',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '26',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '27',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '28',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '29',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '30',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '31',
    sender: 'Atlassian',
    title: 'ForthPage',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '32',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '33',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '34',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '35',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '36',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '37',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '38',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: true,
  },
  {
    id: '39',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
  {
    id: '40',
    sender: 'Atlassian',
    title: 'Introducing Table Visualization',
    text: `Say hello to dynamic charts, Confluence's new integration`,
    date: '16 июн.',
    isViewed: false,
  },
];
